# ░██╗░░░░░░░██╗░█████╗░████████╗███████╗██████╗░██╗░░██╗██╗░░░██╗██████╗░
# ░██║░░██╗░░██║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗██║░░██║██║░░░██║██╔══██╗
# ░╚██╗████╗██╔╝███████║░░░██║░░░█████╗░░██████╔╝███████║██║░░░██║██████╦╝
# ░░████╔═████║░██╔══██║░░░██║░░░██╔══╝░░██╔══██╗██╔══██║██║░░░██║██╔══██╗
# ░░╚██╔╝░╚██╔╝░██║░░██║░░░██║░░░███████╗██║░░██║██║░░██║╚██████╔╝██████╦╝
# ░░░╚═╝░░░╚═╝░░╚═╝░░╚═╝░░░╚═╝░░░╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝░╚═════╝░╚═════╝░

# WaterHub - BungeeCord Hub System
# Support - https://github.com/RDProjectOfficial

# Settings
settings:
  check-updates: true
  permission: "waterhub.reload"
  lobby:
    # The Hub Server (Lobby)
    server: ""
    # Servers on which disabled lobby command (include aliases)
    disabled:
      - ""
    # List of Aliases, you can create besides
    aliases:
      - /lobby
      - /hub

# Messages
messages:
  prefix: "§8• §bWaterHub §8× "
  no-permission: "§cYou do not have permission!"
  config-reloaded: "§bConfiguration successfully reloaded!"
  server:
    connected: "§bYou are connecting to the Lobby..."
    not-found: "§4Configured lobby server is incorrect!"
    already: "§cYou are already connected to the Lobby!"
    disabled: "§cCommand is disabled on this server!"