# ░██╗░░░░░░░██╗░█████╗░████████╗███████╗██████╗░██╗░░██╗██╗░░░██╗██████╗░
# ░██║░░██╗░░██║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗██║░░██║██║░░░██║██╔══██╗
# ░╚██╗████╗██╔╝███████║░░░██║░░░█████╗░░██████╔╝███████║██║░░░██║██████╦╝
# ░░████╔═████║░██╔══██║░░░██║░░░██╔══╝░░██╔══██╗██╔══██║██║░░░██║██╔══██╗
# ░░╚██╔╝░╚██╔╝░██║░░██║░░░██║░░░███████╗██║░░██║██║░░██║╚██████╔╝██████╦╝
# ░░░╚═╝░░░╚═╝░░╚═╝░░╚═╝░░░╚═╝░░░╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝░╚═════╝░╚═════╝░

# WaterHub - BungeeCord Hub System
# Support - https://github.com/RDProjectOfficial

# Settings
settings:
  # Checking for updates (it will send a message indicating whether there are any updates or not)
  check-updates: true
  # Permission for the command /hubreload
  permission: "waterhub.reload"
  # Lobby settings
  lobby:
    # The lobby server, on which people will connect
    server: ""
    # Servers on which the lobby command will be disabled (including aliases)
    disabled:
      - ""
    # List of aliases you can create (in addition to the existing ones)
    aliases:
      - /hub
      - /lobby

# Messages
messages:
  prefix: "§8• §bWaterHub §8× "
  no-permission: "§cYou do not have permission!"
  config-reloaded: "§bConfiguration successfully reloaded!"
  server:
    connected: "§bYou are connecting to the Lobby..."
    already: "§cYou are already connected to the Lobby!"
    disabled: "§cCommand is disabled on this server!"
    not-found: "§4Configured lobby server is incorrect!"